USE [NursingApplication_Phase1]
GO
SET IDENTITY_INSERT [dbo].[tblAdminMaster] ON 
GO
INSERT [dbo].[tblAdminMaster] ([Id], [UserId], [LoginName], [CreatedBy], [Created]) VALUES (100, N'1084219', N'1084219', N'it_sharepoint(it_sharepoint)', CAST(N'2021-11-28T08:31:20.210' AS DateTime))
GO
INSERT [dbo].[tblAdminMaster] ([Id], [UserId], [LoginName], [CreatedBy], [Created]) VALUES (101, N'it_sharepoint', N'it_sharepoint', N'it_sharepoint', CAST(N'2021-11-28T08:32:24.027' AS DateTime))
GO
SET IDENTITY_INSERT [dbo].[tblAdminMaster] OFF
GO
SET IDENTITY_INSERT [dbo].[tblHospitalMasters] ON 
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (11, 10101, N'Chennai Main', 1, CAST(N'2021-11-20T19:21:37.067' AS DateTime), CAST(N'2021-12-24T12:28:58.610' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'Southern Region', 30, 30, 30, 30, 3, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (12, 10102, N'Apollo Specialty Hospitals Teynampet', 1, CAST(N'2021-11-20T19:21:37.070' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'Southern Region', 30, 65, 60, 65, 28, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (13, 10103, N'First Med', 1, CAST(N'2021-11-20T19:21:37.070' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'Southern Region', 30, 65, 60, 65, 26, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (14, 10104, N'Tondiarpet', 1, CAST(N'2021-11-20T19:21:37.070' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'Southern Region', 30, 65, 60, 65, 27, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (15, 10106, N'Apollo Hospitals Aragonda', 1, CAST(N'2021-11-20T19:21:37.070' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'Southern Region', 30, 65, 60, 65, 33, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (16, 10107, N'Apollo Children''s Hospital Chennai', 1, CAST(N'2021-11-20T19:21:37.070' AS DateTime), CAST(N'2021-12-21T22:23:26.467' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'Southern Region', 30, 65, 60, 65, 34, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (17, 10108, N'Vanagaram', 1, CAST(N'2021-11-20T19:21:37.070' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'Southern Region', 30, 65, 60, 65, 18, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (18, 10109, N'Karapakkam', 1, CAST(N'2021-11-20T19:21:37.070' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'Southern Region', 30, 65, 60, 65, 40, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (19, 10110, N'OMR', 1, CAST(N'2021-11-20T19:21:37.070' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'Southern Region', 30, 65, 60, 65, 22, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (20, 10111, N'Apollo Womens Hospitals', 1, CAST(N'2021-11-20T19:21:37.070' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'Southern Region', 30, 65, 60, 65, 53, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (21, 10113, N'Apollo Proton Cancer Centre', 1, CAST(N'2021-11-20T19:21:37.070' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'Southern Region', 30, 65, 60, 65, 54, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (22, 10201, N'Jubilee Hills', 1, CAST(N'2021-11-20T19:21:37.073' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'AP, Telangana Region', 30, 65, 60, 65, NULL, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (23, 10202, N'Hyderguda', 1, CAST(N'2021-11-20T19:21:37.073' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'AP, Telangana Region', 30, 65, 60, 65, 16, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (24, 10204, N'DRDO', 1, CAST(N'2021-11-20T19:21:37.077' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'AP, Telangana Region', 30, 65, 60, 65, 35, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (25, 10209, N'Secunderabad', 1, CAST(N'2021-11-20T19:21:37.077' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'AP, Telangana Region', 30, 65, 60, 65, 14, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (26, 10301, N'Madurai', 1, CAST(N'2021-11-20T19:21:37.077' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'Southern Region', 30, 65, 60, 65, 9, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (27, 10311, N'Karur', 1, CAST(N'2021-11-20T19:21:37.077' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'Southern Region', 30, 65, 60, 65, 37, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (28, 10321, N'Karaikudi', 1, CAST(N'2021-11-20T19:21:37.077' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'Southern Region', 30, 65, 60, 65, 38, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (29, 10331, N'Trichy', 1, CAST(N'2021-11-20T19:21:37.077' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'Southern Region', 30, 65, 60, 65, 17, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (30, 10341, N'Nellore', 1, CAST(N'2021-11-20T19:21:37.080' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'Southern Region', 30, 65, 60, 65, 21, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (31, 10351, N'Mysore', 1, CAST(N'2021-11-20T19:21:37.080' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'Karnataka Region', 30, 65, 60, 65, 10, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (32, 10361, N'Apollo Hospitals Heart & Kidney Centre, Vizag', 1, CAST(N'2021-11-20T19:21:37.080' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'AP, Telangana Region', 30, 65, 60, 65, 12, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (33, 10362, N'Apollo Hospitals Vizag Health City', 1, CAST(N'2021-11-20T19:21:37.080' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'AP, Telangana Region', 30, 65, 60, 65, 24, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (34, 10371, N'Jayanagar', 0, CAST(N'2021-11-20T19:21:37.080' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'Karnataka Region', 30, 65, 60, 65, 39, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (35, 10381, N'Indore', 0, CAST(N'2021-11-20T19:21:37.080' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'AP, Telangana Region', 30, 65, 60, 65, 19, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (36, 10391, N'Apollo Hospitals Seshadripuram', 1, CAST(N'2021-11-20T19:21:37.080' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'Karnataka Region', 30, 65, 60, 65, 23, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (37, 10401, N'Bhubaneswar', 1, CAST(N'2021-11-20T19:21:37.080' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'Orissa and Chattisgarh Region', 30, 65, 60, 65, 13, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (38, 10501, N'Apollo Hospitals Bilaspur', 1, CAST(N'2021-11-20T19:21:37.080' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'Orissa and Chattisgarh Region', 30, 65, 60, 65, 8, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (39, 10551, N'Mumbai', 1, CAST(N'2021-11-20T19:21:37.080' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'Western Region', 30, 65, 60, 65, 41, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (40, 10601, N'Apollo Hospitals Bannerghatta Road', 1, CAST(N'2021-11-20T19:21:37.080' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'Karnataka Region', 30, 65, 60, 65, NULL, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (41, 10701, N'Apollo Hospitals Indraprastha Delhi', 1, CAST(N'2021-11-20T19:21:37.080' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'Northern Region', 30, 65, 60, 65, 4, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (42, 10702, N'Noida', 1, CAST(N'2021-11-20T19:21:37.080' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'Northern Region', 30, 65, 60, 65, 30, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (43, 10801, N'Kolkata', 1, CAST(N'2021-11-20T19:21:37.080' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'Eastern Region', 30, 65, 60, 65, 6, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (44, 10901, N'Kakinada', 1, CAST(N'2021-11-20T19:21:37.080' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'AP, Telangana Region', 30, 65, 60, 65, 29, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (45, 10911, N'Apollo Hospitals, Guwahati', 1, CAST(N'2021-11-20T19:21:37.083' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'Eastern Region', 30, 65, 60, 65, 25, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (46, 10914, N'NMDC Apollo Hospitals, Bacheli', 1, CAST(N'2021-11-20T19:21:37.083' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'Orissa and Chattisgarh Region', 30, 65, 60, 65, 52, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (47, 10917, N'Apollo City Centre Ambavadi', 1, CAST(N'2021-11-20T19:21:37.083' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'Western Region', 30, 65, 60, 65, 36, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (48, 12101, N'Karimnagar', 1, CAST(N'2021-11-20T19:21:37.083' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'AP, Telangana Region', 30, 65, 60, 65, 15, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (49, 12102, N'Apollo Hospitals-Nashik', 1, CAST(N'2021-11-20T19:21:37.083' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'Western Region', 30, 65, 60, 65, 20, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (50, 13001, N'Apollo Medics Hospital,Lucknow', 1, CAST(N'2021-11-20T19:21:37.083' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'Northern Region', 30, 65, 60, 65, 57, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (51, 15104, N'Apollo Heart Center', 1, CAST(N'2021-11-20T19:21:37.083' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'Southern Region', 30, 65, 60, 65, NULL, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (52, 66666, N'Ahmedabad Main Hospital', 1, CAST(N'2021-11-20T19:21:37.083' AS DateTime), CAST(N'2021-12-29T00:07:52.730' AS DateTime), NULL, N'Sumathi Komala(1084219)', N'Western Region', 30, 65, 60, 65, 1, N'85')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (53, 10912, N'Apollo Hospitals  Dhaka', 1, CAST(N'2021-11-24T15:26:45.423' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'Bangladesh Region', 30, 65, 60, 65, 7, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (54, 10913, N'Jehangir Hospital,Pune', 1, CAST(N'2021-11-24T15:26:45.423' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'Western Region', 30, 65, 60, 65, 11, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (55, 10915, N'Apollo BSR Hospitals, Bhilai', 1, CAST(N'2021-11-24T15:26:45.423' AS DateTime), CAST(N'2021-12-29T00:09:15.540' AS DateTime), NULL, N'Sumathi Komala(1084219)', N'Orissa and Chattisgarh Region', 30, 65, 60, 65, 0, N'56')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (56, 10105, N'Sowcarpet', 1, CAST(N'2021-11-24T15:26:45.423' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'Southern Region', 30, 65, 60, 65, 32, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (57, 10916, N'Apollo K H Hospitals, Ranipet', 1, CAST(N'2021-11-24T15:26:45.423' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'Southern Region', 30, 65, 60, 65, 31, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (58, 10203, N'Apollo Emergency Medical Centre Kukatpally', 1, CAST(N'2021-11-24T15:26:45.423' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'AP, Telangana Region', 30, 65, 60, 65, 51, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (59, 10400, N'Apollo Victor Hospitals Goa', 1, CAST(N'2021-11-24T15:26:45.423' AS DateTime), CAST(N'2021-12-21T12:00:13.337' AS DateTime), NULL, N'it_sharepoint(it_sharepoint)', N'', 30, 65, 60, 65, NULL, N'94')
GO
INSERT [dbo].[tblHospitalMasters] ([Id], [HospitalId], [HospitalName], [IsActive], [CreatedOn], [ModifiedOn], [CreatedByUser], [LastModifiedBy], [Region], [EntryLastDate], [VOC_CnCNursingStaff_Target], [VOC_HowPainManaged_Target], [VOC_CallBellResponse_Target], [AniceID], [WOW_ComplianceBilling_Target]) VALUES (60, 14101, N'Apollo Adlux Hospitals, Kochi', 1, CAST(N'2021-11-24T15:26:45.423' AS DateTime), CAST(N'2021-12-28T12:44:18.700' AS DateTime), NULL, N'Sumathi Komala(1084219)', N'Southern Region', 30, 65, 60, 65, 58, N'90')
GO
SET IDENTITY_INSERT [dbo].[tblHospitalMasters] OFF
GO
SET IDENTITY_INSERT [dbo].[tblMasterAllTables] ON 
GO
INSERT [dbo].[tblMasterAllTables] ([Id], [FormCode], [FormName], [FormDisplayName], [TableName], [IsActive], [Created], [ModifiedOn], [LastModifiedBy]) VALUES (1, N'TBL01', N'COE', N'COE Activities', N'tblCOE', 1, CAST(N'2021-11-12T10:10:35.107' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[tblMasterAllTables] ([Id], [FormCode], [FormName], [FormDisplayName], [TableName], [IsActive], [Created], [ModifiedOn], [LastModifiedBy]) VALUES (2, N'TBL02', N'SOP', N'Standard Operating Procedures', N'tblSOP', 1, CAST(N'2021-11-12T10:20:16.977' AS DateTime), CAST(N'2021-12-29T00:12:26.177' AS DateTime), N'Sumathi Komala(1084219)')
GO
INSERT [dbo].[tblMasterAllTables] ([Id], [FormCode], [FormName], [FormDisplayName], [TableName], [IsActive], [Created], [ModifiedOn], [LastModifiedBy]) VALUES (3, N'TBL03', N'Service Excellence Activities', N'Service Excellence Activities', N'tblServiceExcellence', 1, CAST(N'2021-11-12T10:20:16.980' AS DateTime), CAST(N'2021-12-29T00:12:40.150' AS DateTime), N'Sumathi Komala(1084219)')
GO
INSERT [dbo].[tblMasterAllTables] ([Id], [FormCode], [FormName], [FormDisplayName], [TableName], [IsActive], [Created], [ModifiedOn], [LastModifiedBy]) VALUES (4, N'TBL04', N'Consultant Connect', N'Consultant Connect', N'tblConsultantConnect', 1, CAST(N'2021-11-12T10:20:16.980' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[tblMasterAllTables] ([Id], [FormCode], [FormName], [FormDisplayName], [TableName], [IsActive], [Created], [ModifiedOn], [LastModifiedBy]) VALUES (5, N'TBL05', N'Process Improvement', N'Process Improvement', N'tblProcessImprovement', 1, CAST(N'2021-11-12T10:20:16.980' AS DateTime), CAST(N'2021-12-29T00:12:17.680' AS DateTime), N'Sumathi Komala(1084219)')
GO
INSERT [dbo].[tblMasterAllTables] ([Id], [FormCode], [FormName], [FormDisplayName], [TableName], [IsActive], [Created], [ModifiedOn], [LastModifiedBy]) VALUES (6, N'TBL06', N'Top 5 Incidents', N'Top 5 Incidents', N'tblTopIncidents', 1, CAST(N'2021-11-12T10:20:16.980' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[tblMasterAllTables] ([Id], [FormCode], [FormName], [FormDisplayName], [TableName], [IsActive], [Created], [ModifiedOn], [LastModifiedBy]) VALUES (7, N'TBL07', N'Top 5 Complaints', N'Top 5 Complaints', N'tblTopComplaints', 1, CAST(N'2021-11-12T10:20:16.980' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[tblMasterAllTables] ([Id], [FormCode], [FormName], [FormDisplayName], [TableName], [IsActive], [Created], [ModifiedOn], [LastModifiedBy]) VALUES (8, N'TBL08', N'WOW', N'WOW Saving', N'tblWOW', 1, CAST(N'2021-11-12T10:20:16.980' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[tblMasterAllTables] ([Id], [FormCode], [FormName], [FormDisplayName], [TableName], [IsActive], [Created], [ModifiedOn], [LastModifiedBy]) VALUES (9, N'TBL09', N'VOC Score', N' VOC Score', N'tblVOC', 1, CAST(N'2021-11-12T10:20:16.980' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[tblMasterAllTables] ([Id], [FormCode], [FormName], [FormDisplayName], [TableName], [IsActive], [Created], [ModifiedOn], [LastModifiedBy]) VALUES (10, N'TBL10', N'ANICE', N'ANICE Score', N'tblANICE', 1, CAST(N'2021-11-12T10:20:16.980' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[tblMasterAllTables] ([Id], [FormCode], [FormName], [FormDisplayName], [TableName], [IsActive], [Created], [ModifiedOn], [LastModifiedBy]) VALUES (11, N'TBL11', N'Manpower', N'Manpower', N'tblManPower', 1, CAST(N'2021-11-12T10:20:16.980' AS DateTime), CAST(N'2021-12-29T00:12:51.810' AS DateTime), N'Sumathi Komala(1084219)')
GO
INSERT [dbo].[tblMasterAllTables] ([Id], [FormCode], [FormName], [FormDisplayName], [TableName], [IsActive], [Created], [ModifiedOn], [LastModifiedBy]) VALUES (12, N'TBL12', N'Training Initiatives', N'Training Initiatives', N'tblTrainingInitiatives', 1, CAST(N'2021-11-12T10:20:16.980' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[tblMasterAllTables] ([Id], [FormCode], [FormName], [FormDisplayName], [TableName], [IsActive], [Created], [ModifiedOn], [LastModifiedBy]) VALUES (13, N'TBL13', N'English Communication', N'English Communication', N'tblEnglishCommunication', 1, CAST(N'2021-11-12T10:20:16.983' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[tblMasterAllTables] ([Id], [FormCode], [FormName], [FormDisplayName], [TableName], [IsActive], [Created], [ModifiedOn], [LastModifiedBy]) VALUES (14, N'TBL14', N'Reinforcement Communication', N'Reinforcement Communication', N'tblReinforcementCommunication', 1, CAST(N'2021-11-12T10:20:16.983' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[tblMasterAllTables] ([Id], [FormCode], [FormName], [FormDisplayName], [TableName], [IsActive], [Created], [ModifiedOn], [LastModifiedBy]) VALUES (15, N'TBL15', N'Town Hall', N'Town Hall', N'tblTownHall', 1, CAST(N'2021-11-12T10:20:16.983' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[tblMasterAllTables] ([Id], [FormCode], [FormName], [FormDisplayName], [TableName], [IsActive], [Created], [ModifiedOn], [LastModifiedBy]) VALUES (16, N'TBL16', N'CFT', N'CFT', N'tblCFT', 1, CAST(N'2021-11-12T10:20:16.983' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[tblMasterAllTables] ([Id], [FormCode], [FormName], [FormDisplayName], [TableName], [IsActive], [Created], [ModifiedOn], [LastModifiedBy]) VALUES (18, N'TBL18', N'Academic Council', N'Academic Council', N'tblAcademicCouncil', 1, CAST(N'2021-11-12T10:20:16.987' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[tblMasterAllTables] ([Id], [FormCode], [FormName], [FormDisplayName], [TableName], [IsActive], [Created], [ModifiedOn], [LastModifiedBy]) VALUES (19, N'TBL19', N'Best Practices', N'Best Practices', N'tblBestPractices', 1, CAST(N'2021-11-12T10:20:16.987' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[tblMasterAllTables] ([Id], [FormCode], [FormName], [FormDisplayName], [TableName], [IsActive], [Created], [ModifiedOn], [LastModifiedBy]) VALUES (20, N'TBL20', N'Achievements', N'Achievements', N'tblAchievements', 1, CAST(N'2021-11-12T10:20:16.987' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[tblMasterAllTables] ([Id], [FormCode], [FormName], [FormDisplayName], [TableName], [IsActive], [Created], [ModifiedOn], [LastModifiedBy]) VALUES (21, N'TBL21', N'Appreciation', N'Appreciation', N'tblAppreciation', 1, CAST(N'2021-11-12T10:20:16.987' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[tblMasterAllTables] ([Id], [FormCode], [FormName], [FormDisplayName], [TableName], [IsActive], [Created], [ModifiedOn], [LastModifiedBy]) VALUES (22, N'TBL22', N'Challenges', N'Challenges, if any that needs support from any corporate resources ', N'tblChallenges', 1, CAST(N'2021-11-12T10:20:16.990' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[tblMasterAllTables] ([Id], [FormCode], [FormName], [FormDisplayName], [TableName], [IsActive], [Created], [ModifiedOn], [LastModifiedBy]) VALUES (23, N'TBL17', N'R&P', N'Research and Publication (R & P) ', N'tblRP', 1, CAST(N'2021-11-19T20:13:39.767' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[tblMasterAllTables] ([Id], [FormCode], [FormName], [FormDisplayName], [TableName], [IsActive], [Created], [ModifiedOn], [LastModifiedBy]) VALUES (24, N'TBL23', N'Process Standardization', N'Process Standardization', N'tblProcessStandardization', 1, CAST(N'2021-12-16T13:47:43.680' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[tblMasterAllTables] ([Id], [FormCode], [FormName], [FormDisplayName], [TableName], [IsActive], [Created], [ModifiedOn], [LastModifiedBy]) VALUES (25, N'TBL24', N'NHNE', N'NHNE', N'tblNHNE', 1, CAST(N'2021-12-17T10:41:17.290' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[tblMasterAllTables] ([Id], [FormCode], [FormName], [FormDisplayName], [TableName], [IsActive], [Created], [ModifiedOn], [LastModifiedBy]) VALUES (26, N'TBL25', N'Quality Improvement', N'Quality Improvement Project', N'tblQualityImprovement', 1, CAST(N'2021-12-17T10:41:17.310' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[tblMasterAllTables] ([Id], [FormCode], [FormName], [FormDisplayName], [TableName], [IsActive], [Created], [ModifiedOn], [LastModifiedBy]) VALUES (27, N'TBL26', N'Digitization', N'Digitization', N'tblDigitization', 1, CAST(N'2021-12-17T10:41:17.310' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[tblMasterAllTables] ([Id], [FormCode], [FormName], [FormDisplayName], [TableName], [IsActive], [Created], [ModifiedOn], [LastModifiedBy]) VALUES (28, N'TBL27', N'Staff Engagement', N'Staff Engagement', N'tblStaffEngagement', 1, CAST(N'2021-12-17T10:41:17.313' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[tblMasterAllTables] ([Id], [FormCode], [FormName], [FormDisplayName], [TableName], [IsActive], [Created], [ModifiedOn], [LastModifiedBy]) VALUES (29, N'TBL28', N'Report 1', N'Report 1', N'tblReport1', 1, CAST(N'2021-12-17T10:41:17.313' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[tblMasterAllTables] ([Id], [FormCode], [FormName], [FormDisplayName], [TableName], [IsActive], [Created], [ModifiedOn], [LastModifiedBy]) VALUES (30, N'TBL29', N'Report 2', N'Report 2', N'tblReport2', 1, CAST(N'2021-12-17T10:41:17.313' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[tblMasterAllTables] ([Id], [FormCode], [FormName], [FormDisplayName], [TableName], [IsActive], [Created], [ModifiedOn], [LastModifiedBy]) VALUES (31, N'TBL30', N'Report 3', N'Report 3', N'tblReport3', 1, CAST(N'2021-12-17T10:41:17.313' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[tblMasterAllTables] ([Id], [FormCode], [FormName], [FormDisplayName], [TableName], [IsActive], [Created], [ModifiedOn], [LastModifiedBy]) VALUES (32, N'TBL31', N'Report 4', N'Report 4', N'tblReport4', 1, CAST(N'2021-12-17T10:41:17.313' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[tblMasterAllTables] ([Id], [FormCode], [FormName], [FormDisplayName], [TableName], [IsActive], [Created], [ModifiedOn], [LastModifiedBy]) VALUES (33, N'TBL32', N'Report 5', N'Report 5', N'tblReport5', 1, CAST(N'2021-12-17T10:41:17.313' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[tblMasterAllTables] ([Id], [FormCode], [FormName], [FormDisplayName], [TableName], [IsActive], [Created], [ModifiedOn], [LastModifiedBy]) VALUES (34, N'TBL33', N'Report 6', N'Report 6', N'tblReport6', 1, CAST(N'2021-12-17T10:41:17.313' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[tblMasterAllTables] ([Id], [FormCode], [FormName], [FormDisplayName], [TableName], [IsActive], [Created], [ModifiedOn], [LastModifiedBy]) VALUES (35, N'TBL34', N'Report 7', N'Report 7', N'tblReport7', 1, CAST(N'2021-12-17T10:41:17.317' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[tblMasterAllTables] ([Id], [FormCode], [FormName], [FormDisplayName], [TableName], [IsActive], [Created], [ModifiedOn], [LastModifiedBy]) VALUES (36, N'TBL35', N'Report 8', N'Report 8', N'tblReport8', 1, CAST(N'2021-12-17T10:41:17.317' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[tblMasterAllTables] ([Id], [FormCode], [FormName], [FormDisplayName], [TableName], [IsActive], [Created], [ModifiedOn], [LastModifiedBy]) VALUES (37, N'TBL36', N'Report 9', N'Report 9', N'tblReport9', 1, CAST(N'2021-12-17T10:41:17.317' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[tblMasterAllTables] ([Id], [FormCode], [FormName], [FormDisplayName], [TableName], [IsActive], [Created], [ModifiedOn], [LastModifiedBy]) VALUES (38, N'TBL37', N'Report 10', N'Report 10', N'tblReport10', 1, CAST(N'2021-12-17T10:41:17.320' AS DateTime), NULL, NULL)
GO
SET IDENTITY_INSERT [dbo].[tblMasterAllTables] OFF
GO
